# Generated by Django 4.2.2 on 2024-10-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_amount",
        ),
    ]
